default_language_version:
  python: python3

repos:
  - repo: local
    hooks:
      - id: end-of-file-fixer
        name: end-of-file-fixer
        entry: end-of-file-fixer
        language: system
        types: [text]
      - id: check-toml
        name: check-toml
        entry: check-toml
        language: system
        types: [toml]
      - id: check-yaml
        name: check-yaml
        entry: check-yaml
        language: system
        types: [yaml]
      - id: check-merge-conflict
        name: check-merge-conflict
        entry: check-merge-conflict
        language: system
      - id: check-added-large-files
        name: check-added-large-files
        entry: check-added-large-files
        language: system
        exclude: uv.lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.14
    hooks:
      - id: ruff-check
        args:
          [
            --force-exclude,
            --fix,
            --exit-non-zero-on-fix,
            --output-format,
            concise,
          ]
        exclude: ^auto_tutorial_source/
      - id: ruff-format
        exclude: ^auto_tutorials_source/
